const STORAGE_KEY = 'compasso-static-v3';
const OLD_STORAGE_KEY = 'compasso-static';
const COLORS = ['#668981','#d47c63','#7973a5','#c0924e','#b36d83','#5683a0','#648c88'];
const DAYS = ['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
const STAGES = ['Em espera','Aprendendo','Executando'];
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm = value => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
const money = value => Number(value || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const todayISO = () => new Date().toISOString().slice(0,10);
const initials = name => name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();

const seed = {
  alunos:[
    {id:1,nome:'Marina Costa',ini:'MC',cor:'#668981',desde:'2024-03-12',dia:'Segunda',hora:'14:00',duracao:50,plano:'Mensal',valor:420,livro:'Leila Fletcher — Piano Course 2',livrosHistorico:[{nome:'Leila Fletcher — Piano Course 1',inicio:'2024-03-12',fim:'2025-01-20'},{nome:'Leila Fletcher — Piano Course 2',inicio:'2025-01-21'}],musicas:[{nome:'Gymnopédie No. 1',autor:'Erik Satie',status:'Aprendendo',inicio:'2026-06-10'},{nome:'Ode à Alegria',autor:'Beethoven',status:'Executando',inicio:'2025-08-18'}],notas:'Gosta de repertório impressionista. Trabalhar leitura à primeira vista.'},
    {id:2,nome:'Pedro Almeida',ini:'PA',cor:'#d47c63',desde:'2025-02-03',dia:'Segunda',hora:'16:30',duracao:50,plano:'Por aula',valor:115,livro:'Meu Piano é Divertido — Vol. 1',livrosHistorico:[{nome:'Meu Piano é Divertido — Vol. 1',inicio:'2025-02-03'}],musicas:[{nome:'Asa Branca',autor:'Luiz Gonzaga',status:'Aprendendo',inicio:'2026-07-02'}],notas:'Confirmar aula com a mãe pela manhã.'},
    {id:3,nome:'Ana Beatriz',ini:'AB',cor:'#7973a5',desde:'2023-08-15',dia:'Terça',hora:'10:00',duracao:60,plano:'Mensal',valor:480,livro:'Hanon — O Pianista Virtuoso',livrosHistorico:[{nome:'Czerny Op. 599',inicio:'2023-08-15',fim:'2025-10-01'},{nome:'Hanon — O Pianista Virtuoso',inicio:'2025-10-02'}],musicas:[{nome:'Für Elise',autor:'Beethoven',status:'Executando',inicio:'2026-02-12'},{nome:'Prelúdio em Dó Maior',autor:'J. S. Bach',status:'Em espera',inicio:'2026-05-20'}],notas:'Preparando apresentação de outubro.'},
    {id:4,nome:'Lucas Mendes',ini:'LM',cor:'#c0924e',desde:'2024-11-07',dia:'Quarta',hora:'18:00',duracao:50,plano:'Mensal',valor:420,livro:"Alfred's Basic Piano Library 2",livrosHistorico:[{nome:"Alfred's Basic Piano Library 1",inicio:'2024-11-07',fim:'2026-03-14'},{nome:"Alfred's Basic Piano Library 2",inicio:'2026-03-15'}],musicas:[{nome:"Comptine d'un autre été",autor:'Yann Tiersen',status:'Aprendendo',inicio:'2026-07-16'}],notas:'Prefere cifras antes da partitura completa.'},
    {id:5,nome:'Sofia Ribeiro',ini:'SR',cor:'#b36d83',desde:'2026-01-14',dia:'Quinta',hora:'15:30',duracao:60,plano:'Por aula',valor:130,livro:'A Dozen a Day — Livro 1',livrosHistorico:[{nome:'A Dozen a Day — Livro 1',inicio:'2026-01-14'}],musicas:[{nome:'River Flows in You',autor:'Yiruma',status:'Aprendendo',inicio:'2026-04-07'}],notas:'Alterna aulas presenciais e online.'},
    {id:6,nome:'Rafael Nunes',ini:'RN',cor:'#5683a0',desde:'2022-05-09',dia:'Sexta',hora:'09:00',duracao:60,plano:'Mensal',valor:520,livro:'Czerny Op. 599',livrosHistorico:[{nome:'Hanon — O Pianista Virtuoso',inicio:'2022-05-09',fim:'2024-02-10'},{nome:'Czerny Op. 599',inicio:'2024-02-11'}],musicas:[{nome:'Clair de Lune',autor:'Claude Debussy',status:'Executando',inicio:'2025-11-03'}],notas:'Aluno avançado. Foco em interpretação.'}
  ],
  pagamentos:[{id:1,alunoId:1,ref:'Agosto/2026',valor:420,pago:true},{id:2,alunoId:2,ref:'Aula 03/08',valor:115,pago:true},{id:3,alunoId:2,ref:'Aula 10/08',valor:115,pago:false},{id:4,alunoId:3,ref:'Agosto/2026',valor:480,pago:true},{id:5,alunoId:4,ref:'Agosto/2026',valor:420,pago:false},{id:6,alunoId:5,ref:'Aula 06/08',valor:130,pago:true},{id:7,alunoId:5,ref:'Aula 13/08',valor:130,pago:false},{id:8,alunoId:6,ref:'Agosto/2026',valor:520,pago:true}],
  livros:[], repertorio:[]
};

function migrate(raw){
  const freshInstall=!raw||!Array.isArray(raw.alunos), source = freshInstall ? structuredClone(seed) : raw;
  source.alunos = source.alunos.map((a,index)=>{
    const musics=(a.musicas||a.repertorio||[]).map(m=>typeof m==='string'?{nome:m,autor:'',status:'Aprendendo',inicio:todayISO()}:({...m,status:m.status||m.etapa||'Aprendendo'}));
    const history=a.livrosHistorico||a.livros?.map((l,i)=>typeof l==='string'?{nome:l,inicio:a.desde||todayISO(),...(i<a.livros.length-1?{fim:todayISO()}:{})}:l)||[];
    if(a.livro && !history.some(h=>norm(h.nome)===norm(a.livro))) history.push({nome:a.livro,inicio:a.desde||todayISO()});
    const aulas=a.aulas&&Array.isArray(a.aulas)?a.aulas:[{dia:a.dia||'Segunda',hora:a.hora||'10:00',duracao:a.duracao||50}];
    return {...a,id:Number(a.id)||Date.now()+index,ini:a.ini||initials(a.nome),cor:a.cor||COLORS[index%COLORS.length],desde:a.desde||todayISO(),ativo:a.ativo!==false,aulas,dia:aulas[0]?.dia||a.dia||'Segunda',hora:aulas[0]?.hora||a.hora||'10:00',duracao:aulas[0]?.duracao||a.duracao||50,livrosHistorico:history,musicas:musics};
  });
  source.pagamentos=(source.pagamentos||[]).map(p=>({...p,alunoId:Number(p.alunoId??p.aluno)}));
  const bookNames=[...source.alunos.flatMap(a=>a.livrosHistorico.map(h=>h.nome)),...(source.livros||[]).map(x=>typeof x==='string'?x:x.nome)].filter(Boolean);
  const repertoireRows=[...source.alunos.flatMap(a=>a.musicas),...(source.repertorio||[])];
  source.livros=[...new Map(bookNames.map(nome=>[norm(nome),{nome,comentarios:(source.livros||[]).find(x=>norm(x.nome)===norm(nome))?.comentarios||''}])).values()];
  source.repertorio=[...new Map(repertoireRows.map(x=>{const item=typeof x==='string'?{nome:x,autor:'',comentarios:''}:x;return [norm(item.nome),{nome:item.nome,autor:item.autor||'',comentarios:item.comentarios||''}]})).values()];
  source.demoEligible=source.demoEligible===true||freshInstall;
  return source;
}

let data=migrate(JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem(OLD_STORAGE_KEY)||'null'));
data.settings=data.settings||{teacherName:'',schoolName:''};
let ui={page:'inicio',selectedStudent:null,selectedItem:null,selectedPayment:null,selectedClass:null,libraryKind:'musica',search:'',paymentFilter:'all',scheduleDay:'Segunda',paymentMonth:0,moneyVisible:false,agendaView:'week',agendaMonth:0};
const app=$('#app');
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function toast(message){document.body.insertAdjacentHTML('beforeend',`<div class="toast">✓ ${esc(message)}</div>`);setTimeout(()=>$('.toast')?.remove(),2200)}
function photoStyle(photo){const p=typeof photo==='string'?{src:photo}:photo||{};return `background-image:url('${p.src||''}');background-size:${p.zoom||100}%;background-position:${p.x??50}% ${p.y??50}%`}
function photoSource(photo){return typeof photo==='string'?photo:photo?.src||''}
function avatar(a){return a.foto?`<i class="avatar photo" data-photo-view="${esc(photoSource(a.foto))}" style="${photoStyle(a.foto)}" aria-label="Abrir foto de ${esc(a.nome||'perfil')}"></i>`:`<i class="avatar" style="background:${a.cor}">${esc(a.ini)}</i>`}
function thumb(item,kind){return item?.foto?`<i class="thumb" data-photo-view="${esc(photoSource(item.foto))}" style="${photoStyle(item.foto)}" aria-label="Abrir foto"></i>`:`<i class="${kind==='livro'?'book':''}">${kind==='livro'?'▤':'♫'}</i>`}
function nav(){const items=[['inicio','⌂','Início'],['agenda','▦','Agenda'],['alunos','♙','Alunos'],['pagamentos','$','Pagamentos'],['acervo','♫','Acervo']];return `<aside><div class="brand"><b>C</b><strong>Compasso</strong></div>${items.map(x=>`<button class="${ui.page===x[0]&&!ui.selectedStudent&&!ui.selectedItem?'on':''}" data-page="${x[0]}"><i>${x[1]}</i>${x[2]}</button>`).join('')}<button class="user user-button" data-profile-settings>${avatar({ini:'MP',cor:'#244b47'})}<span><b>${esc(data.settings.teacherName||'Professora de piano')}</b><small>${esc(data.settings.schoolName||'Definir escola')}</small></span></button></aside><nav class="mobile-nav">${items.map(x=>`<button class="${ui.page===x[0]&&!ui.selectedStudent&&!ui.selectedItem?'on':''}" data-page="${x[0]}"><i>${x[1]}</i><small>${x[2]}</small></button>`).join('')}</nav>`}
function header(label,title,action=''){return `<header><div><small>${esc(label)}</small><h1>${esc(title)}</h1></div>${action}</header>`}
function searchBox(placeholder='Buscar por palavra-chave'){return `<label class="search">⌕<input id="page-search" value="${esc(ui.search)}" placeholder="${esc(placeholder)}"><button type="button" id="clear-search">${ui.search?'×':'⌕'}</button></label>`}

function legacyHome(){
  const today=data.alunos.filter(a=>a.dia===ui.scheduleDay).sort((a,b)=>a.hora.localeCompare(b.hora));
  return header('ESTÚDIO DE PIANO','Olá 👋','<button class="top-button" aria-label="Notificações">♧</button>')+
  `<section class="welcome"><div><small>VISÃO DO DIA</small><h2>${today.length} ${today.length===1?'aula':'aulas'} hoje</h2><p>Sua rotina musical, organizada e tranquila.</p></div><span>♫</span></section>
  <div class="summary home-summary"><button data-page="agenda"><b>▦</b><span><strong>${data.alunos.length}</strong><small>Alunos ativos na semana</small></span>›</button><button data-page="acervo"><b>♫</b><span><strong>${data.repertorio.length}</strong><small>Peças no repertório</small></span>›</button></div>
  <div class="section-title"><div><small>${esc(ui.scheduleDay.toUpperCase())}</small><h2>Próximas aulas</h2></div><button data-page="agenda">Ver agenda</button></div>
  <div class="rows">${today.length?today.map(studentRow).join(''):'<p class="empty">Nenhuma aula neste dia.</p>'}</div>`;
}
function classSlots(a){return (a.aulas&&a.aulas.length?a.aulas:[{dia:a.dia,hora:a.hora,duracao:a.duracao}]).filter(x=>x.dia&&x.hora)}
function studentRow(a,slot=classSlots(a)[0]){return `<button class="row" data-student="${a.id}"><strong class="time">${esc(slot.hora)}<small>${slot.duracao||50} min</small></strong>${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(a.livro||'Sem livro definido')}</small></span>›</button>`}
function home(){const today=data.alunos.filter(a=>a.ativo!==false&&classSlots(a).some(s=>s.dia===ui.scheduleDay)).flatMap(a=>classSlots(a).filter(s=>s.dia===ui.scheduleDay).map(s=>({a,slot:s}))).sort((x,y)=>x.slot.hora.localeCompare(y.slot.hora));return header('ESTÚDIO DE PIANO',data.settings?.teacherName?`Olá, ${data.settings.teacherName} 👋`:'Olá 👋','<button class="top-button" aria-label="Notificações">♧</button>')+`<section class="welcome"><div><small>VISÃO DO DIA</small><h2>${today.length} ${today.length===1?'aula':'aulas'} hoje</h2><p>Sua rotina musical, organizada e tranquila.</p></div><span>♫</span></section><div class="summary home-summary"><button data-page="agenda"><b>▦</b><span><strong>${data.alunos.filter(a=>a.ativo!==false).length}</strong><small>Alunos ativos na semana</small></span>›</button><button data-page="acervo"><b>♫</b><span><strong>${data.repertorio.length}</strong><small>Peças no repertório</small></span>›</button></div><div class="section-title"><div><small>${esc(ui.scheduleDay.toUpperCase())}</small><h2>Próximas aulas</h2></div><button data-page="agenda">Ver agenda</button></div><div class="rows">${today.length?today.map(x=>studentRow(x.a,x.slot)).join(''):'<p class="empty">Nenhuma aula neste dia.</p>'}</div>`}
function schedule(){const active=data.alunos.filter(a=>a.ativo!==false),days=DAYS.filter(d=>d==='Sábado'||d==='Domingo'?active.some(a=>classSlots(a).some(s=>s.dia===d)):true);return header('ROTINA SEMANAL','Agenda','<button class="add" data-modal="aluno" aria-label="Novo aluno">＋</button>')+`<div class="week-agenda">${days.map(day=>{const entries=active.flatMap(a=>classSlots(a).filter(s=>s.dia===day).map(slot=>({a,slot}))).sort((x,y)=>x.slot.hora.localeCompare(y.slot.hora));return `<section class="week-day"><div><b>${day}</b><small>${entries.length} ${entries.length===1?'aula':'aulas'}</small></div>${entries.length?entries.map(x=>`<button data-student="${x.a.id}"><strong>${esc(x.slot.hora)}</strong><span>${esc(x.a.nome)}</span></button>`).join(''):'<p>—</p>'}</section>`}).join('')}</div>`}
function students(){const active=data.alunos.filter(a=>a.ativo!==false),list=active.filter(a=>norm(a.nome).includes(norm(ui.search)));return header(`${active.length} ALUNOS ATIVOS`,'Alunos','<div class="header-actions"><button class="edit" data-page="inativos">⌁</button><button class="add" data-modal="aluno" aria-label="Novo aluno">＋</button></div>')+searchBox('Buscar aluno')+`<div class="cards">${list.map(a=>`<button class="student" data-student="${a.id}"><div>${avatar(a)}<small>${esc(a.plano)}</small></div><b>${esc(a.nome)}</b><small>${classSlots(a).map(s=>`${esc(s.dia)} ${esc(s.hora)}`).join(' · ')}</small><hr><span><small>▤ ${esc(a.livro||'Sem livro definido')}</small></span></button>`).join('')}</div>`}
function inactiveStudents(){const list=data.alunos.filter(a=>a.ativo===false);return header('HISTÓRICO','Alunos que não têm mais aulas','<button class="close" data-page="alunos">×</button>')+`<div class="cards">${list.length?list.map(a=>`<button class="student" data-student="${a.id}">${avatar(a)}<b>${esc(a.nome)}</b><small>Encerrado em ${esc(a.encerradoEm||'—')}</small></button>`).join(''):'<p class="empty">Nenhum aluno encerrado.</p>'}</div>`}

function secretMoney(value){return `<span class="money ${ui.moneyVisible?'revealed':''}" data-value="${esc(money(value))}"><b>${ui.moneyVisible?esc(money(value)):'••••••'}</b></span>`}
function monthLabel(offset=0){const date=new Date(2026,7+offset,1);return {label:date.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}),key:`${date.toLocaleDateString('pt-BR',{month:'long'}).split(' ')[0].slice(0,3)}/${date.getFullYear()}`}}
function payments(){
  const month=monthLabel(ui.paymentMonth),list=data.pagamentos.filter(p=>norm(p.ref).includes(norm(month.label.split(' ')[0]))||norm(p.ref).includes(norm(month.key))).filter(p=>ui.paymentFilter==='all'||(ui.paymentFilter==='paid'?p.pago:!p.pago));
  const total=data.pagamentos.reduce((s,p)=>s+Number(p.valor),0), paid=data.pagamentos.filter(p=>p.pago).reduce((s,p)=>s+Number(p.valor),0);
  return header('CONTROLE FINANCEIRO','Pagamentos',`<div class="header-actions"><button id="money-eye" class="eye" aria-label="Segure para mostrar valores" title="Segure para mostrar valores">◉</button><button class="add" data-modal="pagamento" aria-label="Novo pagamento">＋</button></div>`)+
  `<div class="month"><button data-month="-1">‹</button><b>${esc(month.label)}</b><button data-month="1">›</button></div><p class="hold-hint">Segure o botão de olho para visualizar os valores.</p><div class="finance"><span><small>Recebido</small>${secretMoney(paid)}</span><span><small>A receber</small>${secretMoney(total-paid)}</span></div><div class="filters">${[['all','Todos'],['paid','Recebidos'],['pending','Pendentes']].map(x=>`<button class="${ui.paymentFilter===x[0]?'active':''}" data-filter="${x[0]}">${x[1]}</button>`).join('')}</div><div class="rows payments">${list.length?list.map(p=>{const a=data.alunos.find(x=>x.id===p.alunoId);if(!a)return '';return `<div class="payment" data-payment="${p.id}"><button class="person" data-student="${a.id}">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(p.ref)} · ${esc(a.plano)}</small></span></button><span class="payment-actions">${secretMoney(p.valor)}${p.pago?'<small class="ok">✓ Recebido</small>':`<button class="confirm" data-pay="${p.id}">Confirmar</button>`}</span></div>`}).join(''):'<p class="empty">Nenhum pagamento registrado neste mês.</p>'}</div>`;
}
function paymentDetail(){const p=data.pagamentos.find(x=>x.id===ui.selectedPayment),a=data.alunos.find(x=>x.id===p?.alunoId);if(!p||!a){ui.selectedPayment=null;return payments()}return header('PAGAMENTO',p.ref,'<button class="close" data-close-payment>×</button>')+`<section class="panel payment-detail"><div class="payment-person">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(a.plano)}</small></span></div><div class="detail-line"><span>Status</span><b class="${p.pago?'ok':'pending-text'}">${p.pago?'Recebido':'Pendente'}</b></div><div class="detail-line"><span>Valor</span>${secretMoney(p.valor)}</div><div class="detail-line"><span>Confirmado em</span><b>${p.pagoEm?esc(p.pagoEm.split('-').reverse().join('/')):'Ainda não confirmado'}</b></div>${p.pago?`<button class="cancel-payment" data-cancel-payment="${p.id}">Cancelar confirmação</button>`:`<button class="save" data-pay="${p.id}">Confirmar pagamento</button>`}</section>`}

function library(){
  const source=ui.libraryKind==='livro'?data.livros:data.repertorio;
  const list=source.filter(item=>norm(`${item.nome} ${item.autor||''}`).includes(norm(ui.search)));
  const label=ui.libraryKind==='livro'?'livro':'música';
  return header('MATERIAL PEDAGÓGICO','Acervo',`<button class="add" data-modal="${label}" aria-label="Adicionar ${label}">＋</button>`)+
  `<div class="switch"><button class="${ui.libraryKind==='musica'?'active':''}" data-kind="musica">♫ Repertório</button><button class="${ui.libraryKind==='livro'?'active':''}" data-kind="livro">▤ Livros</button></div>${searchBox(`Buscar ${label}`)}<div class="library">${list.length?list.map(item=>{const users=currentUsers(ui.libraryKind,item.nome);return `<button data-item="${esc(item.nome)}">${thumb(item,ui.libraryKind)}<span><b>${esc(item.nome)}</b>${item.autor?`<small>${esc(item.autor)}</small>`:''}<em>${users.length} ${users.length===1?'aluno atual':'alunos atuais'}</em></span>›</button>`}).join(''):'<p class="empty">Nenhum item encontrado.</p>'}</div>`;
}
function currentUsers(kind,name){return data.alunos.filter(a=>kind==='livro'?norm(a.livro)===norm(name):a.musicas.some(m=>norm(m.nome)===norm(name)&&!m.fim))}
function historicUsers(kind,name){return data.alunos.filter(a=>kind==='livro'?a.livrosHistorico.some(h=>norm(h.nome)===norm(name)&&h.fim):a.musicas.some(m=>norm(m.nome)===norm(name)&&m.fim))}
function itemDetail(){const {kind,name}=ui.selectedItem;const source=kind==='livro'?data.livros:data.repertorio,item=source.find(x=>norm(x.nome)===norm(name));if(!item){ui.selectedItem=null;return library()}const current=currentUsers(kind,item.nome),history=historicUsers(kind,item.nome);return header(kind==='livro'?'LIVRO':'REPERTÓRIO',item.nome,'<button class="close" data-close-item>×</button>')+`<div class="item-hero">${thumb(item,kind)}<div><small>${kind==='livro'?'MATERIAL DIDÁTICO':'PEÇA MUSICAL'}</small><h2>${esc(item.nome)}</h2>${item.autor?`<p>${esc(item.autor)}</p>`:''}</div></div><section class="panel"><h3>Usando agora · ${current.length}</h3>${current.length?current.map(personLine).join(''):'<p class="empty">Nenhum aluno usando atualmente.</p>'}</section><section class="panel"><h3>Histórico · ${history.length}</h3>${history.length?history.map(personLine).join(''):'<p class="empty">Nenhum aluno no histórico.</p>'}</section><section class="panel"><h3>Comentários gerais</h3><textarea data-item-note="${esc(item.nome)}" data-kind="${kind}" placeholder="Edição, nível, dedilhado ou observações...">${esc(item.comentarios||'')}</textarea></section>`}
function personLine(a){return `<button class="person-line" data-student="${a.id}">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(a.dia)}, ${esc(a.hora)}</small></span>›</button>`}

function studentProfile(){const a=data.alunos.find(x=>x.id===ui.selectedStudent);if(!a){ui.selectedStudent=null;return students()}return header('ALUNO',a.nome,'<div class="header-actions"><button class="edit" data-edit-student="'+a.id+'">✎</button><button class="close" data-page="alunos">×</button></div>')+`<div class="profile">${avatar(a)}<span><small>● ALUNO ATIVO</small><h2>${esc(a.nome)}</h2><p>${esc(a.dia)}, ${esc(a.hora)} · ${a.duracao} min</p></span></div><div class="info"><span><small>Plano</small><b>${esc(a.plano)}</b></span><span><small>Início das aulas</small><b>${esc(a.desde.split('-').reverse().join('/'))}</b></span></div><section class="panel"><div class="panel-head"><h3>Livro atual</h3><button data-assign-book="${a.id}">Alterar</button></div><button class="material-current" data-item="${esc(a.livro)}" data-item-kind="livro"><i class="book">▤</i><span><b>${esc(a.livro||'Sem livro definido')}</b><small>${a.livrosHistorico.length} registro(s) no histórico</small></span>›</button></section><section class="panel"><div class="panel-head"><h3>Repertório atual</h3><button data-assign-music="${a.id}">＋ Música</button></div>${a.musicas.filter(m=>!m.fim).length?a.musicas.filter(m=>!m.fim).map(m=>`<div class="mini"><span>♫</span><button class="music-link" data-item="${esc(m.nome)}" data-item-kind="musica"><b>${esc(m.nome)}</b><small>${esc(m.autor||'')}</small></button><button class="stage" data-stage-student="${a.id}" data-stage-music="${esc(m.nome)}">${esc(m.status)}</button><button class="remove-mini" data-remove-music="${esc(m.nome)}" data-student-id="${a.id}" title="Concluir e arquivar">×</button></div>`).join(''):'<p class="empty">Nenhuma música ativa.</p>'}</section><section class="panel"><h3>Observações</h3><textarea data-student-note="${a.id}">${esc(a.notas||'')}</textarea></section><section class="panel"><h3>Histórico de livros</h3>${a.livrosHistorico.map(h=>`<div class="history"><i></i><span><b>${esc(h.nome)}</b><small>${h.fim?'Concluído':'Em uso atualmente'}</small></span></div>`).join('')}</section><section class="panel"><h3>Histórico de repertório</h3>${a.musicas.map(m=>`<div class="history"><i></i><span><b>${esc(m.nome)}</b><small>${m.fim?'Arquivado':esc(m.status)}</small></span></div>`).join('')}</section>`}

function render(){let body=ui.selectedClass?classDetail():ui.selectedStudent?studentProfile():ui.selectedItem?itemDetail():ui.selectedPayment?paymentDetail():ui.page==='inicio'?home():ui.page==='agenda'?schedule():ui.page==='alunos'?students():ui.page==='inativos'?inactiveStudents():ui.page==='pagamentos'?payments():library();app.innerHTML=`<main class="layout">${nav()}<section class="content">${body}</section></main>`;bind()}

function bind(){
  $$('[data-page]').forEach(el=>el.onclick=()=>{ui.page=el.dataset.page;ui.selectedStudent=null;ui.selectedItem=null;ui.selectedPayment=null;ui.selectedClass=null;ui.search='';render()});
  $$('[data-profile-settings]').forEach(el=>el.addEventListener('click',openProfileSettings));
  $$('[data-student]').forEach(el=>el.onclick=()=>{ui.selectedStudent=Number(el.dataset.student);ui.selectedItem=null;ui.selectedClass=null;render()});
  $$('[data-day]').forEach(el=>el.onclick=()=>{ui.scheduleDay=el.dataset.day;render()});
  $$('[data-kind]').filter(el=>el.tagName==='BUTTON').forEach(el=>el.onclick=()=>{ui.libraryKind=el.dataset.kind;ui.search='';render()});
  $$('[data-item]').forEach(el=>el.onclick=()=>{ui.selectedItem={kind:el.dataset.itemKind||ui.libraryKind,name:el.dataset.item};ui.selectedStudent=null;render()});
  $('[data-close-item]')?.addEventListener('click',()=>{ui.selectedItem=null;render()});
  $('[data-close-payment]')?.addEventListener('click',()=>{ui.selectedPayment=null;render()});
  $('#page-search')?.addEventListener('input',e=>{ui.search=e.target.value;const pos=e.target.selectionStart;render();const next=$('#page-search');next?.focus();next?.setSelectionRange(pos,pos)});
  $('#clear-search')?.addEventListener('click',()=>{ui.search='';render()});
  $$('[data-filter]').forEach(el=>el.onclick=()=>{ui.paymentFilter=el.dataset.filter;render()});
  $$('[data-month]').forEach(el=>el.onclick=()=>{ui.paymentMonth+=Number(el.dataset.month);ui.moneyVisible=false;render()});
  $$('[data-payment]').forEach(el=>el.onclick=()=>{ui.selectedPayment=Number(el.dataset.payment);render()});
  $$('[data-pay]').forEach(el=>el.onclick=e=>{e.stopPropagation();const p=data.pagamentos.find(x=>x.id===Number(el.dataset.pay));if(p){p.pago=true;p.pagoEm=todayISO();save();toast('Pagamento confirmado');render()}});
  $$('[data-cancel-payment]').forEach(el=>el.onclick=()=>{const p=data.pagamentos.find(x=>x.id===Number(el.dataset.cancelPayment));if(p){p.pago=false;delete p.pagoEm;save();toast('Confirmação cancelada');render()}});
  $$('[data-modal]').forEach(el=>el.onclick=()=>{openModal(el.dataset.modal);if(el.dataset.modal==='aluno')setTimeout(setupPlanValueLabel)});
  $$('[data-edit-student]').forEach(el=>el.onclick=()=>{openStudentModal(Number(el.dataset.editStudent));setTimeout(setupPlanValueLabel)});
  $$('[data-stop-student]').forEach(el=>el.onclick=()=>stopStudent(Number(el.dataset.stopStudent)));
  $$('[data-assign-book]').forEach(el=>el.onclick=()=>openAssignmentModal('livro',Number(el.dataset.assignBook)));
  $$('[data-assign-music]').forEach(el=>el.onclick=()=>openAssignmentModal('musica',Number(el.dataset.assignMusic)));
  $$('[data-stage-student]').forEach(el=>el.onclick=()=>cycleStage(Number(el.dataset.stageStudent),el.dataset.stageMusic));
  $$('[data-remove-music]').forEach(el=>el.onclick=()=>archiveMusic(Number(el.dataset.studentId),el.dataset.removeMusic));
  $$('[data-student-note]').forEach(el=>el.onchange=()=>{const a=data.alunos.find(x=>x.id===Number(el.dataset.studentNote));a.notas=el.value;save();toast('Observações salvas')});
  $$('[data-item-note]').forEach(el=>el.onchange=()=>{const list=el.dataset.kind==='livro'?data.livros:data.repertorio;const item=list.find(x=>norm(x.nome)===norm(el.dataset.itemNote));item.comentarios=el.value;save();toast('Comentários salvos')});
  $$('[data-class]').forEach(el=>el.onclick=()=>{ui.selectedClass=el.dataset.class;render()});
  $$('[data-class-status]').forEach(el=>el.onclick=()=>setClassStatus(el.dataset.classStatus));
  $('[data-close-class]')?.addEventListener('click',()=>{ui.selectedClass=null;render()});
  $('[data-reschedule]')?.addEventListener('click',openRescheduleModal);
  $('[data-edit-item]')?.addEventListener('click',openItemEditModal);
  $$('[data-agenda-view]').forEach(el=>el.onclick=()=>{ui.agendaView=el.dataset.agendaView;render()});
  $$('[data-agenda-month]').forEach(el=>el.onclick=()=>{ui.agendaMonth+=Number(el.dataset.agendaMonth);render()});
  $$('[data-photo-view]').forEach(el=>el.onclick=e=>{e.preventDefault();e.stopPropagation();openPhotoViewer(el.dataset.photoView)});
  $('[data-class-note]')?.addEventListener('change',e=>{const r=data.classRecords?.find(x=>x.id===ui.selectedClass);if(r){r.notes=e.target.value;save();toast('Comentário da aula salvo')}});
  $('[data-payment-note]')?.addEventListener('change',e=>{const p=data.pagamentos.find(x=>x.id===ui.selectedPayment);if(p){p.notes=e.target.value;save();toast('Comentário do pagamento salvo')}});
  const eye=$('#money-eye');if(eye){const show=e=>{e.preventDefault();ui.moneyVisible=true;updateMoneyDisplay()},hide=e=>{e.preventDefault();ui.moneyVisible=false;updateMoneyDisplay()};['pointerdown','touchstart','mousedown'].forEach(n=>eye.addEventListener(n,show,{passive:false}));['pointerup','pointercancel','pointerleave','touchend','mouseup','blur'].forEach(n=>eye.addEventListener(n,hide,{passive:false}));}
}
function updateMoneyDisplay(){$$('.money').forEach(el=>{el.classList.toggle('revealed',ui.moneyVisible);$('b',el).textContent=ui.moneyVisible?el.dataset.value:'••••••'})}
function cycleStage(studentId,musicName){const a=data.alunos.find(x=>x.id===studentId),m=a.musicas.find(x=>norm(x.nome)===norm(musicName)&&!x.fim);if(!m)return;m.status=STAGES[(STAGES.indexOf(m.status)+1)%STAGES.length];save();toast('Etapa atualizada');render()}
function archiveMusic(studentId,musicName){const a=data.alunos.find(x=>x.id===studentId),m=a.musicas.find(x=>norm(x.nome)===norm(musicName)&&!x.fim);if(!m)return;m.fim=todayISO();save();toast('Música movida para o histórico');render()}

function modalShell(title,content){document.body.insertAdjacentHTML('beforeend',`<div class="modal-back"><form class="modal"><button type="button" class="modal-close" aria-label="Fechar">×</button><small>COMPASSO</small><h2>${esc(title)}</h2>${content}<button class="save" type="submit">Salvar</button></form></div>`);$('.modal-close').onclick=closeModal;$('.modal-back').onpointerdown=e=>{if(e.target===e.currentTarget)closeModal()}}
function closeModal(){$('.modal-back')?.remove()}
function field(label,id,type='text',value='',extra=''){return `<label>${esc(label)}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function selectField(label,id,options,value){return `<label>${esc(label)}<select id="${id}">${options.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`}
function openModal(type){if(type==='aluno')return openStudentModal();if(type==='pagamento')return openPaymentModal();return openCatalogModal(type)}

function openStudentModal(studentId){const existing=data.alunos.find(x=>x.id===studentId);modalShell(existing?'Editar aluno':'Novo aluno',`${field('Nome completo','f-name','text',existing?.nome||'','required')}${field('Data de início','f-since','date',existing?.desde||todayISO())}<div class="form-grid">${selectField('Dia da aula','f-day',DAYS,existing?.dia||'Segunda')}${field('Horário','f-time','time',existing?.hora||'10:00')}</div><div class="form-grid">${selectField('Plano','f-plan',['Mensal','Por aula'],existing?.plano||'Mensal')}${field('Valor combinado','f-value','number',existing?.valor||'', 'min="0" step="0.01"')}</div>${autocompleteField('Livro atual','f-book',existing?.livro||'',data.livros.map(x=>x.nome),'Digite para buscar livros já cadastrados')}${field('Observações','f-note','text',existing?.notas||'')}`);bindAutocomplete('f-book',data.livros.map(x=>x.nome));$('.modal').onsubmit=e=>{e.preventDefault();const values={nome:$('#f-name').value.trim(),desde:$('#f-since').value,dia:$('#f-day').value,hora:$('#f-time').value,plano:$('#f-plan').value,valor:Number($('#f-value').value||0),livro:$('#f-book').value.trim()||'Sem livro definido',notas:$('#f-note').value.trim()};if(existing){const oldBook=existing.livro;Object.assign(existing,{...values,livro:oldBook,ini:initials(values.nome)});if(norm(oldBook)!==norm(values.livro))changeBook(existing,values.livro)}else{const a={id:Date.now(),...values,ini:initials(values.nome),cor:COLORS[data.alunos.length%COLORS.length],duracao:50,livrosHistorico:[],musicas:[]};ensureBook(values.livro);a.livrosHistorico=[{nome:values.livro,inicio:todayISO()}];data.alunos.push(a)}ensureBook(values.livro);save();closeModal();toast(existing?'Aluno atualizado':'Aluno adicionado');render()}}
function openPaymentModal(){modalShell('Registrar pagamento',`${selectField('Aluno','f-student',data.alunos.map(a=>`${a.id}|${a.nome}`),'')}${field('Referência','f-ref','text','','placeholder="Ex.: Setembro/2026" required')}<div class="form-grid">${field('Valor','f-value','number','','min="0" step="0.01" required')}${selectField('Situação','f-paid',['Pendente','Recebido'],'Pendente')}</div>`);$('#f-student').innerHTML=data.alunos.map(a=>`<option value="${a.id}">${esc(a.nome)}</option>`).join('');$('.modal').onsubmit=e=>{e.preventDefault();data.pagamentos.push({id:Date.now(),alunoId:Number($('#f-student').value),ref:$('#f-ref').value.trim(),valor:Number($('#f-value').value),pago:$('#f-paid').value==='Recebido'});save();closeModal();toast('Pagamento registrado');render()}}
function openCatalogModal(type){const isBook=type==='livro';modalShell(isBook?'Cadastrar livro':'Cadastrar música',`${autocompleteField(isBook?'Título do livro':'Título da música','f-title','',isBook?data.livros.map(x=>x.nome):data.repertorio.map(x=>x.nome),'Digite para verificar se já existe')}${isBook?'':field('Compositor ou artista','f-author')}${field('Comentários gerais','f-comments')}`);bindAutocomplete('f-title',isBook?data.livros.map(x=>x.nome):data.repertorio.map(x=>x.nome));$('.modal').onsubmit=e=>{e.preventDefault();const name=$('#f-title').value.trim(),list=isBook?data.livros:data.repertorio,duplicate=list.find(x=>norm(x.nome)===norm(name));if(duplicate){showDuplicate(`“${duplicate.nome}” já está cadastrado. Selecione a sugestão existente para evitar duplicatas.`);return}list.push({nome:name,autor:isBook?'':$('#f-author').value.trim(),comentarios:$('#f-comments').value.trim()});save();closeModal();toast(isBook?'Livro cadastrado':'Música cadastrada');render()}}
function openAssignmentModal(type,studentId){const a=data.alunos.find(x=>x.id===studentId),isBook=type==='livro',source=isBook?data.livros:data.repertorio;modalShell(isBook?'Alterar livro':'Adicionar ao repertório',`${autocompleteField(isBook?'Livro':'Música','f-title','',source.map(x=>x.nome),'Digite para ver sugestões existentes')}${isBook?'':field('Compositor ou artista','f-author')}`);bindAutocomplete('f-title',source.map(x=>x.nome),selected=>{if(!isBook){const item=data.repertorio.find(x=>norm(x.nome)===norm(selected));if(item)$('#f-author').value=item.autor||''}});$('.modal').onsubmit=e=>{e.preventDefault();const name=$('#f-title').value.trim();if(!name)return;if(isBook){ensureBook(name);changeBook(a,name)}else{let item=data.repertorio.find(x=>norm(x.nome)===norm(name));if(!item){item={nome:name,autor:$('#f-author').value.trim(),comentarios:''};data.repertorio.push(item)}if(a.musicas.some(m=>norm(m.nome)===norm(name)&&!m.fim)){showDuplicate('Esta música já está no repertório atual deste aluno.');return}a.musicas.push({nome:item.nome,autor:item.autor,status:'Aprendendo',inicio:todayISO()})}save();closeModal();toast(isBook?'Livro atualizado':'Música adicionada');render()}}
function autocompleteField(label,id,value,items,placeholder){return `<label class="autocomplete">${esc(label)}<input id="${id}" value="${esc(value)}" placeholder="${esc(placeholder)}" autocomplete="off" required><div class="suggestions" id="${id}-suggestions"></div></label>`}
function bindAutocomplete(id,items,onSelect=()=>{}){const input=$(`#${id}`),box=$(`#${id}-suggestions`);const refresh=()=>{const q=norm(input.value);const matches=q?items.filter(x=>norm(x).includes(q)).slice(0,6):[];box.innerHTML=matches.map(x=>`<button type="button" data-suggestion="${esc(x)}"><b>${esc(x)}</b><small>Já cadastrado — usar este</small></button>`).join('');$$('[data-suggestion]',box).forEach(btn=>btn.onclick=()=>{input.value=btn.dataset.suggestion;box.innerHTML='';onSelect(btn.dataset.suggestion)})};input.oninput=refresh;input.onfocus=refresh}
function showDuplicate(message){let note=$('.duplicate-note');if(!note){$('.save').insertAdjacentHTML('beforebegin','<p class="duplicate-note"></p>');note=$('.duplicate-note')}note.textContent=message}
function ensureBook(name){if(!data.livros.some(x=>norm(x.nome)===norm(name)))data.livros.push({nome:name,comentarios:''})}
function changeBook(student,newBook){if(norm(student.livro)===norm(newBook))return;const current=[...student.livrosHistorico].reverse().find(h=>!h.fim);if(current)current.fim=todayISO();student.livro=newBook;student.livrosHistorico.push({nome:newBook,inicio:todayISO()})}
function openCatalogModal(type){const isBook=type==='livro';const list=isBook?data.livros:data.repertorio;modalShell(isBook?'Cadastrar livro':'Cadastrar música',`${autocompleteField(isBook?'Título do livro':'Título da música','f-title','',list.map(x=>x.nome),'Digite para verificar duplicatas')}${isBook?'':field('Compositor ou artista','f-author')}${photoField(isBook?'Foto da capa':'Foto da música','f-photo')}${field('Comentários gerais','f-comments')}`);bindAutocomplete('f-title',list.map(x=>x.nome));let photoData='';$('#f-photo')?.addEventListener('change',e=>readPhoto(e.target,file=>photoData=file));$('.modal').onsubmit=e=>{e.preventDefault();const name=$('#f-title').value.trim(),duplicate=list.find(x=>norm(x.nome)===norm(name));if(duplicate){showDuplicate(`“${duplicate.nome}” já está cadastrado. Selecione a sugestão existente para evitar duplicatas.`);return}list.push({nome:name,autor:isBook?'':$('#f-author').value.trim(),comentarios:$('#f-comments').value.trim(),foto:photoData});save();closeModal();toast(isBook?'Livro cadastrado':'Música cadastrada');render()}}

function slotMarkup(slot={dia:'Segunda',hora:'10:00',duracao:50},index){return `<div class="slot-row" data-slot-row><select data-slot-day>${DAYS.map(d=>`<option ${d===slot.dia?'selected':''}>${d}</option>`).join('')}</select><input type="time" data-slot-time value="${esc(slot.hora)}"><input type="number" data-slot-duration min="10" max="240" step="5" value="${slot.duracao||50}"><button type="button" data-remove-slot="${index}" aria-label="Remover horário">×</button></div>`}
function openStudentModal(studentId){const existing=data.alunos.find(x=>x.id===studentId);const slots=existing?.aulas?.length?existing.aulas:[{dia:existing?.dia||'Segunda',hora:existing?.hora||'10:00',duracao:existing?.duracao||50}];modalShell(existing?'Editar aluno':'Novo aluno',`${field('Nome completo','f-name','text',existing?.nome||'','required')}${field('Data de início','f-since','date',existing?.desde||todayISO())}${photoField('Foto do aluno','f-photo')}<div class="panel compact"><div class="panel-head"><h3>Horários fixos</h3><button type="button" id="add-slot">＋ Horário</button></div><div id="slot-list">${slots.map(slotMarkup).join('')}</div></div><div class="form-grid">${selectField('Plano','f-plan',['Mensal','Por aula'],existing?.plano||'Mensal')}${field('Valor combinado','f-value','number',existing?.valor||'', 'min="0" step="0.01"')}</div>${autocompleteField('Livro atual','f-book',existing?.livro||'',data.livros.map(x=>x.nome),'Sugestões de livros cadastrados')}${field('Observações','f-note','text',existing?.notas||'')}`);bindAutocomplete('f-book',data.livros.map(x=>x.nome));let photoData=existing?.foto||'';$('#f-photo')?.addEventListener('change',e=>readPhoto(e.target,file=>photoData=file));$('#add-slot').onclick=()=>{$('#slot-list').insertAdjacentHTML('beforeend',slotMarkup({dia:'Segunda',hora:'10:00',duracao:50},$('[data-slot-row]',$('.modal')).length));bindSlotRemove()};bindSlotRemove();$('.modal').onsubmit=e=>{e.preventDefault();const values={nome:$('#f-name').value.trim(),desde:$('#f-since').value,plano:$('#f-plan').value,valor:Number($('#f-value').value||0),livro:$('#f-book').value.trim()||'Sem livro definido',notas:$('#f-note').value.trim(),foto:photoData};const aulas=$$('[data-slot-row]',$('.modal')).map(row=>({dia:$('[data-slot-day]',row).value,hora:$('[data-slot-time]',row).value,duracao:Number($('[data-slot-duration]',row).value)||50})).filter(x=>x.hora);if(!aulas.length){toast('Adicione ao menos um horário');return}values.aulas=aulas;values.dia=aulas[0].dia;values.hora=aulas[0].hora;values.duracao=aulas[0].duracao;if(existing){const oldBook=existing.livro;Object.assign(existing,{...values,livro:oldBook,ini:initials(values.nome)});if(norm(oldBook)!==norm(values.livro))changeBook(existing,values.livro)}else{const a={id:Date.now(),...values,ini:initials(values.nome),cor:COLORS[data.alunos.length%COLORS.length],ativo:true,livrosHistorico:[],musicas:[]};ensureBook(values.livro);a.livrosHistorico=[{nome:values.livro,inicio:todayISO()}];data.alunos.push(a)}ensureBook(values.livro);save();closeModal();toast(existing?'Aluno atualizado':'Aluno adicionado');render()}}
function bindSlotRemove(){$$('[data-remove-slot]').forEach(btn=>btn.onclick=()=>{const rows=$$('[data-slot-row]',$('.modal'));if(rows.length>1)btn.closest('[data-slot-row]').remove()})}
function readPhoto(input,callback){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>openCropper(reader.result,callback);reader.readAsDataURL(file)}
function photoField(label,id){return `<label>${esc(label)}<input id="${id}" type="file" accept="image/*" capture="environment"><small>Opcional — tire uma foto ou escolha uma imagem.</small></label>`}
function openProfileSettings(){modalShell('Dados da professora',`${field('Seu nome','f-teacher','text',data.settings.teacherName||'','placeholder="Ex.: Maria Silva"')}${field('Nome da escola','f-school','text',data.settings.schoolName||'','placeholder="Ex.: Escola de Música Harmonia"')}`);$('.modal').onsubmit=e=>{e.preventDefault();data.settings.teacherName=$('#f-teacher').value.trim();data.settings.schoolName=$('#f-school').value.trim();save();closeModal();toast('Dados atualizados');render()}}
function studentProfile(){const a=data.alunos.find(x=>x.id===ui.selectedStudent);if(!a){ui.selectedStudent=null;return students()}const active=a.ativo!==false;return header('ALUNO',a.nome,`<div class="header-actions"><button class="edit" data-edit-student="${a.id}">✎</button><button class="close" data-page="${active?'alunos':'inativos'}">×</button></div>`)+`<div class="profile">${avatar(a)}<span><small>${active?'● ALUNO ATIVO':'○ ALUNO ENCERRADO'}</small><h2>${esc(a.nome)}</h2><p>${classSlots(a).map(s=>`${esc(s.dia)}, ${esc(s.hora)} · ${s.duracao||50} min`).join(' · ')}</p></span></div><div class="info"><span><small>Plano</small><b>${esc(a.plano)}</b></span><span><small>Início das aulas</small><b>${esc(a.desde.split('-').reverse().join('/'))}</b></span></div>${active?`<section class="panel"><div class="panel-head"><h3>Horários fixos</h3><button data-edit-student="${a.id}">Editar</button></div>${classSlots(a).map(s=>`<div class="detail-line"><span>${esc(s.dia)}</span><b>${esc(s.hora)} · ${s.duracao||50} min</b></div>`).join('')}</section>`:''}<section class="panel"><div class="panel-head"><h3>Livro atual</h3>${active?`<button data-assign-book="${a.id}">Alterar</button>`:''}</div><button class="material-current" data-item="${esc(a.livro)}" data-item-kind="livro">${thumb(data.livros.find(x=>norm(x.nome)===norm(a.livro)),'livro')}<span><b>${esc(a.livro||'Sem livro definido')}</b><small>${a.livrosHistorico.length} registro(s) no histórico</small></span>›</button></section>${active?`<section class="panel"><div class="panel-head"><h3>Repertório atual</h3><button data-assign-music="${a.id}">＋ Música</button></div>${a.musicas.filter(m=>!m.fim).length?a.musicas.filter(m=>!m.fim).map(m=>`<div class="mini"><span>♫</span><button class="music-link" data-item="${esc(m.nome)}" data-item-kind="musica"><b>${esc(m.nome)}</b><small>${esc(m.autor||'')}</small></button><button class="stage" data-stage-student="${a.id}" data-stage-music="${esc(m.nome)}">${esc(m.status)}</button><button class="remove-mini" data-remove-music="${esc(m.nome)}" data-student-id="${a.id}" title="Concluir e arquivar">×</button></div>`).join(''):'<p class="empty">Nenhuma música ativa.</p>'}</section>`:''}<section class="panel"><h3>Observações</h3><textarea data-student-note="${a.id}">${esc(a.notas||'')}</textarea></section><section class="panel"><h3>Histórico de livros</h3>${a.livrosHistorico.map(h=>`<div class="history"><i></i><span><b>${esc(h.nome)}</b><small>${h.fim?'Concluído':'Em uso atualmente'}</small></span></div>`).join('')}</section><section class="panel"><h3>Histórico de repertório</h3>${a.musicas.map(m=>`<div class="history"><i></i><span><b>${esc(m.nome)}</b><small>${m.fim?'Arquivado':esc(m.status)}</small></span></div>`).join('')}</section><button class="danger-action" data-stop-student="${a.id}">${active?'Encerrar aulas deste aluno':'Reativar este aluno'}</button>`}

function openCropper(src,onSave){
  let zoom=100,x=50,y=50,start=null;
  document.body.insertAdjacentHTML('beforeend',`<div class="modal-back crop-back"><section class="modal crop-modal"><small>FOTO</small><h2>Ajustar miniatura</h2><p>Arraste a imagem para posicionar. Use o controle para aproximar.</p><div class="crop-frame"><img src="${src}" alt="Prévia da foto"></div><label>Aproximação<input class="crop-zoom" type="range" min="100" max="260" value="100"></label><div class="crop-actions"><button type="button" class="close-crop">Cancelar</button><button type="button" class="save crop-save">Usar foto</button></div></section></div>`);
  const back=$('.crop-back'),frame=$('.crop-frame',back),img=$('img',frame),slider=$('.crop-zoom',back);
  const paint=()=>{img.style.width=`${zoom}%`;img.style.left=`${x}%`;img.style.top=`${y}%`;img.style.transform='translate(-50%,-50%)'};
  slider.oninput=()=>{zoom=Number(slider.value);paint()};
  frame.onpointerdown=e=>{start={px:e.clientX,py:e.clientY,x,y};frame.setPointerCapture?.(e.pointerId)};
  frame.onpointermove=e=>{if(!start)return;x=Math.max(0,Math.min(100,start.x+(e.clientX-start.px)/2));y=Math.max(0,Math.min(100,start.y+(e.clientY-start.py)/2));paint()};
  frame.onpointerup=()=>start=null;$('.close-crop',back).onclick=()=>back.remove();$('.crop-save',back).onclick=()=>{onSave({src,zoom,x,y});back.remove()};paint();
}
function nav(){const items=[['inicio','⌂','Início'],['agenda','▦','Agenda'],['alunos','♙','Alunos'],['pagamentos','$','Pagamentos'],['acervo','♫','Acervo']];const teacher={ini:'MP',cor:'#244b47',foto:data.settings?.foto,nome:data.settings?.teacherName||'Professora de piano'};return `<aside><div class="brand"><b>C</b><strong>Compasso</strong></div>${items.map(x=>`<button class="${ui.page===x[0]&&!ui.selectedStudent&&!ui.selectedItem?'on':''}" data-page="${x[0]}"><i>${x[1]}</i>${x[2]}</button>`).join('')}<button class="user user-button" data-profile-settings>${avatar(teacher)}<span><b>${esc(data.settings.teacherName||'Professora de piano')}</b><small>${esc(data.settings.schoolName||'Definir escola')}</small></span></button></aside><nav class="mobile-nav">${items.map(x=>`<button class="${ui.page===x[0]&&!ui.selectedStudent&&!ui.selectedItem?'on':''}" data-page="${x[0]}"><i>${x[1]}</i><small>${x[2]}</small></button>`).join('')}</nav>`}
function openProfileSettings(){let photoData=data.settings.foto||'';modalShell('Dados da professora',`${field('Seu nome','f-teacher','text',data.settings.teacherName||'','placeholder="Ex.: Maria Silva"')}${field('Nome da escola','f-school','text',data.settings.schoolName||'','placeholder="Ex.: Escola de Música Harmonia"')}${photoField('Sua foto','f-photo')}`);$('#f-photo')?.addEventListener('change',e=>readPhoto(e.target,file=>photoData=file));$('.modal').onsubmit=e=>{e.preventDefault();data.settings.teacherName=$('#f-teacher').value.trim();data.settings.schoolName=$('#f-school').value.trim();data.settings.foto=photoData;save();closeModal();toast('Dados atualizados');render()}}
function populateDemo(){
  if(data.demoKurtSeyit||data.demoEligible!==true)return;
  const portraits='assets/students-demo.png',cover='assets/book-demo.png';
  data.settings={...data.settings,teacherName:data.settings.teacherName||'Lale Aydin',schoolName:data.settings.schoolName||'Escola de Música Pera',foto:data.settings.foto||{src:'assets/teacher-demo.png',zoom:100,x:50,y:50}};
  const themed=[['Aylin Demir',{src:portraits,zoom:200,x:0,y:0}],['Nikolai Arslan',{src:portraits,zoom:200,x:100,y:0}],['Elena Yildiz',{src:portraits,zoom:200,x:0,y:100}],['Kemal Petrović',{src:portraits,zoom:200,x:100,y:100}]];
  data.alunos.slice(0,4).forEach((a,i)=>{a.nome=themed[i][0];a.ini=initials(a.nome);a.foto=themed[i][1]});
  data.alunos[0].aulas=[{dia:'Segunda',hora:'14:00',duracao:50},{dia:'Quinta',hora:'14:00',duracao:50}];
  data.alunos[1].aulas=[{dia:'Terça',hora:'16:30',duracao:50},{dia:'Sexta',hora:'16:30',duracao:50}];
  const add=(nome,aulas,livro,plano,valor,foto,ativo=true)=>{if(data.alunos.some(a=>a.nome===nome))return;data.alunos.push({id:Date.now()+data.alunos.length,nome,ini:initials(nome),cor:COLORS[data.alunos.length%COLORS.length],desde:'2026-02-10',aulas,dia:aulas[0].dia,hora:aulas[0].hora,duracao:aulas[0].duracao,plano,valor,livro,livrosHistorico:[{nome:livro,inicio:'2026-02-10'}],musicas:[{nome:'Noites sobre o Bósforo',autor:'Repertório tradicional',status:'Aprendendo',inicio:'2026-04-02'}],notas:'Exemplo inspirado no ambiente de Istambul e Crimeia do início do século XX.',foto,ativo,encerradoEm:ativo?undefined:'2026-06-30'})};
  add('Meryem Volkov',[{dia:'Quarta',hora:'11:00',duracao:50},{dia:'Sábado',hora:'10:00',duracao:50}],'Pequenas peças do Bósforo','Mensal',450,{src:portraits,zoom:200,x:0,y:100});
  add('Yusuf Kerem',[{dia:'Quinta',hora:'18:30',duracao:50}],'Caderno de Pera','Por aula',130,{src:portraits,zoom:200,x:100,y:0});
  add('Seda Romanova',[{dia:'Terça',hora:'09:00',duracao:50}],'Pequenas peças do Bósforo','Mensal',420,{src:portraits,zoom:200,x:0,y:0},false);
  add('Orhan Belov',[{dia:'Sexta',hora:'19:00',duracao:50}],'Caderno de Pera','Por aula',120,{src:portraits,zoom:200,x:100,y:100},false);
  ['Pequenas peças do Bósforo','Caderno de Pera','Canções de Yalta'].forEach(nome=>{if(!data.livros.some(x=>norm(x.nome)===norm(nome)))data.livros.push({nome,comentarios:'Material de demonstração.',foto:{src:cover,zoom:100,x:50,y:50}})});
  ['Noites sobre o Bósforo','Valsa de Yalta','Carta de Pera'].forEach(nome=>{if(!data.repertorio.some(x=>norm(x.nome)===norm(nome)))data.repertorio.push({nome,autor:'Repertório de demonstração',comentarios:'Peça de demonstração.',foto:{src:cover,zoom:160,x:50,y:50}})});
  data.demoKurtSeyit=true;data.demoEligible=false;save();
}
function localISO(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function monthDate(offset=0){const now=new Date();return new Date(now.getFullYear(),now.getMonth()+offset,1)}
function monthKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
function monthLabel(offset=0){const date=monthDate(offset),label=date.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});return {date,label:label[0].toUpperCase()+label.slice(1),key:monthKey(date)}}
function datesForSlotInMonth(date,slot){const target=DAYS.indexOf(slot.dia)+1,out=[],last=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();for(let d=1;d<=last;d++){const day=new Date(date.getFullYear(),date.getMonth(),d);if(day.getDay()===target%7)out.push(localISO(day))}return out}
function ensurePaymentsForMonth(offset=0){
  const date=monthDate(offset),key=monthKey(date),monthName=date.toLocaleDateString('pt-BR',{month:'long'}),year=date.getFullYear();
  data.alunos.filter(a=>a.ativo!==false).forEach(a=>{
    if(a.plano==='Mensal'){
      const autoKey=`${a.id}-monthly-${key}`,existing=data.pagamentos.find(p=>p.autoKey===autoKey||(!p.autoKey&&p.alunoId===a.id&&norm(p.ref).includes(norm(monthName))));
      if(existing){existing.autoKey=autoKey;existing.dueDate=existing.dueDate||`${key}-01`}else data.pagamentos.push({id:Date.now()+Math.random(),alunoId:a.id,ref:`${monthName[0].toUpperCase()+monthName.slice(1)}/${year}`,valor:a.valor,pago:false,dueDate:`${key}-01`,autoKey});
    }else classSlots(a).forEach((slot,slotIndex)=>datesForSlotInMonth(date,slot).forEach(day=>{
      const autoKey=`${a.id}-class-${day}-${slotIndex}`;if(!data.pagamentos.some(p=>p.autoKey===autoKey))data.pagamentos.push({id:Date.now()+Math.random(),alunoId:a.id,ref:`Aula ${day.split('-').reverse().slice(0,2).join('/')}`,valor:a.valor,pago:false,dueDate:day,autoKey});
    }));
  });save();
}
function payments(){
  ensurePaymentsForMonth(ui.paymentMonth);const month=monthLabel(ui.paymentMonth),allMonth=data.pagamentos.filter(p=>p.dueDate?.startsWith(month.key)||(norm(p.ref).includes(norm(month.label.split(' ')[0]))&&String(p.ref).includes(String(month.date.getFullYear())))),list=allMonth.filter(p=>ui.paymentFilter==='all'||(ui.paymentFilter==='paid'?p.pago:!p.pago)),total=allMonth.reduce((s,p)=>s+Number(p.valor),0),paid=allMonth.filter(p=>p.pago).reduce((s,p)=>s+Number(p.valor),0);
  return header('CONTROLE FINANCEIRO','Pagamentos',`<div class="header-actions"><button id="money-eye" class="eye floating-eye" aria-label="Segure para mostrar valores" title="Segure para mostrar valores">◉</button><button class="add" data-modal="pagamento" aria-label="Novo pagamento">＋</button></div>`)+`<div class="month"><button data-month="-1">‹</button><b>${esc(month.label)}</b><button data-month="1">›</button></div><p class="hold-hint">Segure o botão de olho para visualizar os valores.</p><div class="finance"><span><small>Recebido</small>${secretMoney(paid)}</span><span><small>A receber</small>${secretMoney(total-paid)}</span></div><div class="filters">${[['all','Todos'],['paid','Recebidos'],['pending','Pendentes']].map(x=>`<button class="${ui.paymentFilter===x[0]?'active':''}" data-filter="${x[0]}">${x[1]}</button>`).join('')}</div><div class="rows payments">${list.length?list.map(p=>{const a=data.alunos.find(x=>x.id===p.alunoId);if(!a)return '';return `<div class="payment" data-payment="${p.id}"><button class="person" data-student="${a.id}">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(p.ref)} · ${esc(a.plano)}</small></span></button><span class="payment-actions">${secretMoney(p.valor)}${p.pago?'<small class="ok">✓ Recebido</small>':`<button class="confirm" data-pay="${p.id}">Confirmar</button>`}</span></div>`}).join(''):'<p class="empty">Nenhum pagamento registrado neste mês.</p>'}</div>`;
}
function stopStudent(studentId){const a=data.alunos.find(x=>x.id===studentId);if(!a)return;if(a.ativo===false){a.ativo=true;delete a.encerradoEm;ensurePaymentsForMonth(0);save();toast('Aluno reativado');render();return}const now=new Date(),start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,end=localISO(new Date(now.getFullYear(),now.getMonth()+1,0));a.ativo=false;a.encerradoEm=todayISO();data.pagamentos=data.pagamentos.filter(p=>p.alunoId!==a.id||!p.dueDate||p.dueDate<=end);if(confirm('Excluir também os pagamentos deste aluno no mês atual? Isso inclui pagamentos já confirmados.'))data.pagamentos=data.pagamentos.filter(p=>p.alunoId!==a.id||!p.dueDate||p.dueDate<start||p.dueDate>end);save();toast('Aulas encerradas e pagamentos futuros removidos');render()}
function weekStart(){const now=new Date(),day=now.getDay()||7;return new Date(now.getFullYear(),now.getMonth(),now.getDate()-day+1)}
function ensureWeekRecords(){data.classRecords=data.classRecords||[];const monday=weekStart();data.alunos.filter(a=>a.ativo!==false).forEach(a=>classSlots(a).forEach((slot,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+DAYS.indexOf(slot.dia));const day=localISO(date),id=`regular-${a.id}-${day}-${index}`;if(!data.classRecords.some(r=>r.id===id))data.classRecords.push({id,studentId:a.id,date:day,time:slot.hora,duration:slot.duracao||50,status:'pending',day:slot.dia})}));save()}
function schedule(){ensureWeekRecords();const monday=weekStart(),sunday=new Date(monday);sunday.setDate(monday.getDate()+6);const from=localISO(monday),to=localISO(sunday),records=data.classRecords.filter(r=>r.date>=from&&r.date<=to&&data.alunos.some(a=>a.id===r.studentId&&a.ativo!==false)),days=DAYS.filter((d,i)=>i<5||records.some(r=>r.day===d));return header('ROTINA SEMANAL','Agenda','<button class="add" data-modal="aluno" aria-label="Novo aluno">＋</button>')+`<div class="week-agenda">${days.map(day=>{const entries=records.filter(r=>r.day===day).sort((a,b)=>a.time.localeCompare(b.time));return `<section class="week-day"><div><b>${day}</b><small>${entries.length} ${entries.length===1?'aula':'aulas'}</small></div>${entries.length?entries.map(r=>{const a=data.alunos.find(x=>x.id===r.studentId);return `<button data-class="${r.id}"><strong>${esc(r.time)}</strong><span>${esc(a?.nome||'Aluno')}</span>${r.rescheduled?'<em>Reagendada</em>':''}</button>`}).join(''):'<p>—</p>'}</section>`}).join('')}</div>`}
function classDetail(){ensureWeekRecords();const r=data.classRecords.find(x=>x.id===ui.selectedClass),a=data.alunos.find(x=>x.id===r?.studentId);if(!r||!a){ui.selectedClass=null;return schedule()}const labels={pending:'Não registrada',held:'Aula realizada',teacher_cancel:'Cancelada pela professora',student_cancel:'Cancelada pelo aluno',no_show:'Aluno não compareceu'};return header('AULA',a.nome,'<button class="close" data-close-class>×</button>')+`<div class="profile">${avatar(a)}<span><small>${r.rescheduled?'● AULA REAGENDADA':'AULA DA SEMANA'}</small><h2>${esc(r.day)}, ${esc(r.time)}</h2><p>${r.duration||50} minutos · ${esc(r.date.split('-').reverse().join('/'))}</p></span></div><section class="panel"><h3>Situação da aula</h3><div class="class-statuses">${[['held','✓','Aconteceu'],['teacher_cancel','×','Professora cancelou'],['student_cancel','×','Aluno cancelou'],['no_show','!','Não compareceu']].map(x=>`<button class="${r.status===x[0]?'active':''}" data-class-status="${x[0]}"><i>${x[1]}</i><span>${x[2]}</span></button>`).join('')}</div><p class="status-note">Atual: <b>${labels[r.status]||labels.pending}</b></p>${['teacher_cancel','student_cancel'].includes(r.status)?`<button class="save" data-reschedule>${r.rescheduledTo?'Alterar reagendamento':'Reagendar aula'}</button>`:''}</section><button class="person-line" data-student="${a.id}">${avatar(a)}<span><b>Abrir cadastro do aluno</b><small>Livro, repertório e observações</small></span>›</button>`}
function setClassStatus(status){const r=data.classRecords?.find(x=>x.id===ui.selectedClass);if(!r)return;r.status=status;r.updatedAt=todayISO();save();toast('Situação da aula atualizada');render()}
function openRescheduleModal(){const original=data.classRecords.find(x=>x.id===ui.selectedClass);if(!original)return;modalShell('Reagendar aula',`${field('Nova data','f-class-date','date',original.rescheduledTo?.date||todayISO(),'required')}${field('Novo horário','f-class-time','time',original.rescheduledTo?.time||original.time,'required')}${field('Duração em minutos','f-class-duration','number',original.duration||50,'min="10" max="240" step="5"')}`);$('.modal').onsubmit=e=>{e.preventDefault();const date=$('#f-class-date').value,time=$('#f-class-time').value,duration=Number($('#f-class-duration').value)||50,day=DAYS[(new Date(`${date}T12:00:00`).getDay()+6)%7],id=`rescheduled-${original.studentId}-${date}-${time.replace(':','')}`;data.classRecords=data.classRecords.filter(r=>r.originId!==original.id);data.classRecords.push({id,originId:original.id,studentId:original.studentId,date,time,duration,day,status:'pending',rescheduled:true});original.rescheduledTo={date,time};save();closeModal();toast('Aula reagendada');ui.selectedClass=id;render()}}
function itemDetail(){const {kind,name}=ui.selectedItem,source=kind==='livro'?data.livros:data.repertorio,item=source.find(x=>norm(x.nome)===norm(name));if(!item){ui.selectedItem=null;return library()}const current=currentUsers(kind,item.nome),history=historicUsers(kind,item.nome);return header(kind==='livro'?'LIVRO':'REPERTÓRIO',item.nome,`<div class="header-actions"><button class="edit" data-edit-item aria-label="Editar">✎</button><button class="close" data-close-item>×</button></div>`)+`<div class="item-hero">${thumb(item,kind)}<div><small>${kind==='livro'?'MATERIAL DIDÁTICO':'PEÇA MUSICAL'}</small><h2>${esc(item.nome)}</h2>${item.autor?`<p>${esc(item.autor)}</p>`:''}</div></div><section class="panel"><h3>Usando agora · ${current.length}</h3>${current.length?current.map(personLine).join(''):'<p class="empty">Nenhum aluno usando atualmente.</p>'}</section><section class="panel"><h3>Histórico · ${history.length}</h3>${history.length?history.map(personLine).join(''):'<p class="empty">Nenhum aluno no histórico.</p>'}</section><section class="panel"><h3>Comentários gerais</h3><textarea data-item-note="${esc(item.nome)}" data-kind="${kind}">${esc(item.comentarios||'')}</textarea></section>`}
function openItemEditModal(){const {kind,name}=ui.selectedItem,list=kind==='livro'?data.livros:data.repertorio,item=list.find(x=>norm(x.nome)===norm(name));if(!item)return;let photoData=item.foto||'';modalShell(kind==='livro'?'Editar livro':'Editar repertório',`${field('Nome','f-item-name','text',item.nome,'required')}${kind==='musica'?field('Compositor ou artista','f-item-author','text',item.autor||''):''}${photoField('Foto ou capa','f-item-photo')}${field('Comentários gerais','f-item-comments','text',item.comentarios||'')}`);$('#f-item-photo')?.addEventListener('change',e=>readPhoto(e.target,file=>photoData=file));$('.modal').onsubmit=e=>{e.preventDefault();const old=item.nome,newName=$('#f-item-name').value.trim();if(list.some(x=>x!==item&&norm(x.nome)===norm(newName))){showDuplicate('Já existe outro item com esse nome.');return}item.nome=newName;item.comentarios=$('#f-item-comments').value.trim();item.foto=photoData;if(kind==='musica')item.autor=$('#f-item-author').value.trim();data.alunos.forEach(a=>{if(kind==='livro'){if(norm(a.livro)===norm(old))a.livro=newName;a.livrosHistorico.forEach(h=>{if(norm(h.nome)===norm(old))h.nome=newName})}else a.musicas.forEach(m=>{if(norm(m.nome)===norm(old)){m.nome=newName;m.autor=item.autor}})});ui.selectedItem={kind,name:newName};save();closeModal();toast('Item atualizado');render()}}
function setupPlanValueLabel(){const plan=$('#f-plan'),value=$('#f-value');if(!plan||!value)return;const refresh=()=>{const label=value.closest('label');if(label?.firstChild)label.firstChild.textContent=plan.value==='Por aula'?'Valor por aula':'Valor mensal'};plan.addEventListener('change',refresh);refresh()}
function paymentRow(p,a){return `<div class="payment" data-payment="${p.id}"><button class="person" data-student="${a.id}">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(p.ref)}</small></span></button><span class="payment-actions">${secretMoney(p.valor)}${p.pago?'<small class="ok">✓ Recebido</small>':`<button class="confirm" data-pay="${p.id}">Confirmar</button>`}</span></div>`}
function payments(){
  ensurePaymentsForMonth(ui.paymentMonth);const month=monthLabel(ui.paymentMonth),allMonth=data.pagamentos.filter(p=>p.dueDate?.startsWith(month.key)||(norm(p.ref).includes(norm(month.label.split(' ')[0]))&&String(p.ref).includes(String(month.date.getFullYear())))),visible=allMonth.filter(p=>ui.paymentFilter==='all'||(ui.paymentFilter==='paid'?p.pago:!p.pago)),monthly=visible.filter(p=>data.alunos.find(a=>a.id===p.alunoId)?.plano==='Mensal'),perClass=visible.filter(p=>data.alunos.find(a=>a.id===p.alunoId)?.plano==='Por aula'),total=allMonth.reduce((s,p)=>s+Number(p.valor),0),paid=allMonth.filter(p=>p.pago).reduce((s,p)=>s+Number(p.valor),0),groups=[...new Set(perClass.map(p=>p.alunoId))].map(id=>({student:data.alunos.find(a=>a.id===id),items:perClass.filter(p=>p.alunoId===id)})).filter(g=>g.student);
  return header('CONTROLE FINANCEIRO','Pagamentos',`<div class="header-actions"><button id="money-eye" class="eye floating-eye" aria-label="Segure para mostrar valores" title="Segure para mostrar valores">◉</button><button class="add" data-modal="pagamento" aria-label="Novo pagamento">＋</button></div>`)+`<div class="month"><button data-month="-1">‹</button><b>${esc(month.label)}</b><button data-month="1">›</button></div><p class="hold-hint">Segure o botão de olho para visualizar os valores.</p><div class="finance"><span><small>Recebido</small>${secretMoney(paid)}</span><span><small>A receber</small>${secretMoney(total-paid)}</span></div><div class="filters">${[['all','Todos'],['paid','Recebidos'],['pending','Pendentes']].map(x=>`<button class="${ui.paymentFilter===x[0]?'active':''}" data-filter="${x[0]}">${x[1]}</button>`).join('')}</div><section class="payment-plan"><div class="section-title"><div><small>PLANO MENSAL</small><h2>Mensalidades</h2></div><span>${monthly.length}</span></div><div class="rows payments">${monthly.length?monthly.map(p=>paymentRow(p,data.alunos.find(a=>a.id===p.alunoId))).join(''):'<p class="empty">Nenhuma mensalidade neste filtro.</p>'}</div></section><section class="payment-plan per-class"><div class="section-title"><div><small>PAGAMENTO POR AULA</small><h2>Aulas avulsas</h2></div><span>${perClass.length}</span></div>${groups.length?groups.map(g=>`<article class="payment-cluster"><div class="cluster-head">${avatar(g.student)}<span><b>${esc(g.student.nome)}</b><small>${g.items.length} ${g.items.length===1?'aula':'aulas'} · ${esc(money(g.student.valor))} por aula</small></span><div><small>Subtotal</small>${secretMoney(g.items.reduce((s,p)=>s+Number(p.valor),0))}</div></div><div class="rows payments">${g.items.sort((a,b)=>(a.dueDate||'').localeCompare(b.dueDate||'')).map(p=>paymentRow(p,g.student)).join('')}</div></article>`).join(''):'<p class="empty">Nenhum pagamento por aula neste filtro.</p>'}</section>`;
}
function paymentDetail(){const p=data.pagamentos.find(x=>x.id===ui.selectedPayment),a=data.alunos.find(x=>x.id===p?.alunoId);if(!p||!a){ui.selectedPayment=null;return payments()}return header('PAGAMENTO',p.ref,'<button class="close" data-close-payment>×</button>')+`<section class="panel payment-detail"><div class="payment-person">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(a.plano)}${a.plano==='Por aula'?` · ${esc(money(a.valor))} por aula`:''}</small></span></div><div class="detail-line"><span>Status</span><b class="${p.pago?'ok':'pending-text'}">${p.pago?'Recebido':'Pendente'}</b></div><div class="detail-line"><span>Valor</span>${secretMoney(p.valor)}</div><div class="detail-line"><span>Confirmado em</span><b>${p.pagoEm?esc(p.pagoEm.split('-').reverse().join('/')):'Ainda não confirmado'}</b></div><label class="detail-note">Comentário<textarea data-payment-note placeholder="Comprovante, forma de pagamento ou observação...">${esc(p.notes||'')}</textarea></label>${p.pago?`<button class="cancel-payment" data-cancel-payment="${p.id}">Cancelar confirmação</button>`:`<button class="save" data-pay="${p.id}">Confirmar pagamento</button>`}</section>`}
function schedule(){ensureWeekRecords();const monday=weekStart(),sunday=new Date(monday);sunday.setDate(monday.getDate()+6);const from=localISO(monday),to=localISO(sunday),records=data.classRecords.filter(r=>r.date>=from&&r.date<=to&&data.alunos.some(a=>a.id===r.studentId&&a.ativo!==false)),days=DAYS.filter((d,i)=>i<5||records.some(r=>r.day===d));return header('ROTINA SEMANAL','Agenda','<button class="add" data-modal="aluno" aria-label="Novo aluno">＋</button>')+`<div class="week-agenda">${days.map(day=>{const entries=records.filter(r=>r.day===day).sort((a,b)=>a.time.localeCompare(b.time));return `<section class="week-day"><div><b>${day}</b><small>${entries.length} ${entries.length===1?'aula':'aulas'}</small></div>${entries.length?entries.map(r=>{const a=data.alunos.find(x=>x.id===r.studentId);return `<button class="class-entry status-${r.status||'pending'}" data-class="${r.id}"><strong>${esc(r.time)}</strong><span>${esc(a?.nome||'Aluno')}</span>${r.rescheduled?'<em>Reagendada</em>':''}</button>`}).join(''):'<p>—</p>'}</section>`}).join('')}</div>`}
function classDetail(){ensureWeekRecords();const r=data.classRecords.find(x=>x.id===ui.selectedClass),a=data.alunos.find(x=>x.id===r?.studentId);if(!r||!a){ui.selectedClass=null;return schedule()}const labels={pending:'Não registrada',held:'Aula realizada',teacher_cancel:'Cancelada pela professora',student_cancel:'Cancelada pelo aluno',no_show:'Aluno não compareceu'};return header('AULA',a.nome,'<button class="close" data-close-class>×</button>')+`<div class="profile">${avatar(a)}<span><small>${r.rescheduled?'● AULA REAGENDADA':'AULA DA SEMANA'}</small><h2>${esc(r.day)}, ${esc(r.time)}</h2><p>${r.duration||50} minutos · ${esc(r.date.split('-').reverse().join('/'))}</p></span></div><section class="panel"><h3>Situação da aula</h3><div class="class-statuses">${[['held','✓','Aconteceu'],['teacher_cancel','×','Professora cancelou'],['student_cancel','×','Aluno cancelou'],['no_show','!','Não compareceu']].map(x=>`<button class="${r.status===x[0]?'active':''}" data-class-status="${x[0]}"><i>${x[1]}</i><span>${x[2]}</span></button>`).join('')}</div><p class="status-note">Atual: <b>${labels[r.status]||labels.pending}</b></p>${['teacher_cancel','student_cancel'].includes(r.status)?`<button class="save" data-reschedule>${r.rescheduledTo?'Alterar reagendamento':'Reagendar aula'}</button>`:''}</section><section class="panel"><h3>Comentário da aula</h3><textarea data-class-note placeholder="Conteúdo trabalhado, exercícios, comportamento ou lembretes...">${esc(r.notes||'')}</textarea></section><button class="person-line" data-student="${a.id}">${avatar(a)}<span><b>Abrir cadastro do aluno</b><small>Livro, repertório e observações</small></span>›</button>`}
function photoField(label,id,current=''){const src=photoSource(current);return `<div class="photo-editor"><span>${esc(label)}</span><div class="photo-editor-preview ${src?'has-photo':''}" id="${id}-preview" ${src?`style="${photoStyle(current)}"`:''}><i>♬</i><label for="${id}" class="camera-action" aria-label="Abrir câmera"><span>⌾</span><input id="${id}" type="file" accept="image/*" capture="environment"></label></div><small>Toque na câmera para fotografar.</small></div>`}
function bindPhotoEditor(id,current,onChange){const input=$(`#${id}`),preview=$(`#${id}-preview`);if(!input)return;input.onchange=()=>readPhoto(input,photo=>{if(preview){preview.classList.add('has-photo');preview.setAttribute('style',photoStyle(photo))}onChange(photo)})}
function readPhoto(input,callback){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onerror=()=>toast('Não foi possível abrir esta foto');reader.onload=()=>openCropper(reader.result,callback);reader.readAsDataURL(file)}
function openCropper(src,onSave){let zoom=100,x=50,y=50,start=null;document.body.insertAdjacentHTML('beforeend',`<div class="modal-back crop-back"><section class="modal crop-modal"><small>FOTO</small><h2>Ajustar miniatura</h2><p>Arraste para posicionar e use o controle para aproximar.</p><div class="crop-frame"><img src="${src}" alt="Prévia da foto"></div><label>Aproximação<input class="crop-zoom" type="range" min="100" max="280" value="100"></label><div class="crop-actions"><button type="button" class="close-crop">Cancelar</button><button type="button" class="save crop-save">Usar foto</button></div></section></div>`);const back=$('.crop-back'),frame=$('.crop-frame',back),img=$('img',frame),slider=$('.crop-zoom',back),paint=()=>{img.style.width=`${zoom}%`;img.style.left=`${x}%`;img.style.top=`${y}%`;img.style.transform='translate(-50%,-50%)'};slider.oninput=()=>{zoom=Number(slider.value);paint()};frame.onpointerdown=e=>{start={px:e.clientX,py:e.clientY,x,y};frame.setPointerCapture?.(e.pointerId)};frame.onpointermove=e=>{if(!start)return;x=Math.max(0,Math.min(100,start.x+(e.clientX-start.px)/2));y=Math.max(0,Math.min(100,start.y+(e.clientY-start.py)/2));paint()};frame.onpointerup=()=>start=null;$('.close-crop',back).onclick=()=>back.remove();$('.crop-save',back).onclick=()=>{const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),size=512,nw=img.naturalWidth,nh=img.naturalHeight,scale=Math.max(size/nw,size/nh)*(zoom/100),dw=nw*scale,dh=nh*scale,dx=(size-dw)*(x/100),dy=(size-dh)*(y/100);canvas.width=canvas.height=size;ctx.drawImage(img,dx,dy,dw,dh);const result=canvas.toDataURL('image/jpeg',.82);onSave(result);back.remove();toast('Foto ajustada')};img.onload=paint;paint()}
function openPhotoViewer(src){if(!src)return;document.body.insertAdjacentHTML('beforeend',`<div class="photo-viewer" role="dialog" aria-label="Foto ampliada"><button type="button" aria-label="Fechar">×</button><img src="${src}" alt="Foto ampliada"></div>`);const viewer=$('.photo-viewer');viewer.onclick=e=>{if(e.target===viewer||e.target.tagName==='BUTTON')viewer.remove()}}
function home(){const today=data.alunos.filter(a=>a.ativo!==false&&classSlots(a).some(s=>s.dia===ui.scheduleDay)).flatMap(a=>classSlots(a).filter(s=>s.dia===ui.scheduleDay).map(s=>({a,slot:s}))).sort((x,y)=>x.slot.hora.localeCompare(y.slot.hora));return header('ESTÚDIO DE PIANO',data.settings?.teacherName?`Olá, ${data.settings.teacherName} 👋`:'Sua semana','<button class="top-button profile-shortcut" data-profile-settings aria-label="Editar perfil da professora">♙</button>')+`<section class="welcome"><div><small>VISÃO DO DIA</small><h2>${today.length} ${today.length===1?'aula':'aulas'} hoje</h2><p>Sua rotina musical, organizada e tranquila.</p></div><span>♫</span></section><div class="summary home-summary"><button data-page="agenda"><b>▦</b><span><strong>${data.alunos.filter(a=>a.ativo!==false).length}</strong><small>Alunos ativos na semana</small></span>›</button><button data-page="acervo"><b>♫</b><span><strong>${data.repertorio.length}</strong><small>Peças no repertório</small></span>›</button></div><div class="section-title"><div><small>${esc(ui.scheduleDay.toUpperCase())}</small><h2>Próximas aulas</h2></div><button data-page="agenda">Ver agenda</button></div><div class="rows">${today.length?today.map(x=>studentRow(x.a,x.slot)).join(''):'<p class="empty">Nenhuma aula neste dia.</p>'}</div>`}
function openProfileSettings(){let photoData=data.settings.foto||'';modalShell('Dados da professora',`${photoField('Foto da professora','f-photo',photoData)}${field('Seu nome','f-teacher','text',data.settings.teacherName||'','placeholder="Ex.: Maria Silva"')}${field('Nome da escola','f-school','text',data.settings.schoolName||'','placeholder="Ex.: Escola de Música Harmonia"')}`);bindPhotoEditor('f-photo',photoData,file=>photoData=file);$('.modal').onsubmit=e=>{e.preventDefault();data.settings.teacherName=$('#f-teacher').value.trim();data.settings.schoolName=$('#f-school').value.trim();data.settings.foto=photoData;save();closeModal();toast('Dados atualizados');render()}}
function openStudentModal(studentId){const existing=data.alunos.find(x=>x.id===studentId),slots=existing?.aulas?.length?existing.aulas:[{dia:existing?.dia||'Segunda',hora:existing?.hora||'10:00',duracao:existing?.duracao||50}];let photoData=existing?.foto||'';modalShell(existing?'Editar aluno':'Novo aluno',`${photoField('Foto do aluno','f-photo',photoData)}${field('Nome completo','f-name','text',existing?.nome||'','required')}${field('Data de início','f-since','date',existing?.desde||todayISO())}<div class="panel compact"><div class="panel-head"><h3>Horários fixos</h3><button type="button" id="add-slot">＋ Horário</button></div><div id="slot-list">${slots.map(slotMarkup).join('')}</div></div><div class="form-grid">${selectField('Plano','f-plan',['Mensal','Por aula'],existing?.plano||'Mensal')}${field('Valor combinado','f-value','number',existing?.valor||'', 'min="0" step="0.01"')}</div>${autocompleteField('Livro atual','f-book',existing?.livro||'',data.livros.map(x=>x.nome),'Escolha um livro existente ou cadastre um novo')}${field('Observações','f-note','text',existing?.notas||'')}`);bindPhotoEditor('f-photo',photoData,file=>photoData=file);bindAutocomplete('f-book',data.livros.map(x=>x.nome));$('#add-slot').onclick=()=>{$('#slot-list').insertAdjacentHTML('beforeend',slotMarkup({dia:'Segunda',hora:'10:00',duracao:50},$$('[data-slot-row]',$('.modal')).length));bindSlotRemove()};bindSlotRemove();setupPlanValueLabel();$('.modal').onsubmit=e=>{e.preventDefault();const values={nome:$('#f-name').value.trim(),desde:$('#f-since').value,plano:$('#f-plan').value,valor:Number($('#f-value').value||0),livro:$('#f-book').value.trim()||'Sem livro definido',notas:$('#f-note').value.trim(),foto:photoData},aulas=$$('[data-slot-row]',$('.modal')).map(row=>({dia:$('[data-slot-day]',row).value,hora:$('[data-slot-time]',row).value,duracao:Number($('[data-slot-duration]',row).value)||50})).filter(x=>x.hora);if(!aulas.length){toast('Adicione ao menos um horário');return}values.aulas=aulas;values.dia=aulas[0].dia;values.hora=aulas[0].hora;values.duracao=aulas[0].duracao;if(existing){const oldBook=existing.livro;Object.assign(existing,{...values,livro:oldBook,ini:initials(values.nome)});if(norm(oldBook)!==norm(values.livro))changeBook(existing,values.livro)}else{const a={id:Date.now(),...values,ini:initials(values.nome),cor:COLORS[data.alunos.length%COLORS.length],ativo:true,livrosHistorico:[{nome:values.livro,inicio:todayISO()}],musicas:[]};data.alunos.push(a)}ensureBook(values.livro);save();closeModal();toast(existing?'Aluno atualizado':'Aluno adicionado');render()}}
function openItemEditModal(){const {kind,name}=ui.selectedItem,list=kind==='livro'?data.livros:data.repertorio,item=list.find(x=>norm(x.nome)===norm(name));if(!item)return;let photoData=item.foto||'';modalShell(kind==='livro'?'Editar livro':'Editar repertório',`${photoField(kind==='livro'?'Foto da capa':'Imagem do repertório','f-item-photo',photoData)}${field('Nome','f-item-name','text',item.nome,'required')}${kind==='musica'?field('Compositor ou artista','f-item-author','text',item.autor||''):''}${field('Comentários gerais','f-item-comments','text',item.comentarios||'')}`);bindPhotoEditor('f-item-photo',photoData,file=>photoData=file);$('.modal').onsubmit=e=>{e.preventDefault();const old=item.nome,newName=$('#f-item-name').value.trim();if(list.some(x=>x!==item&&norm(x.nome)===norm(newName))){showDuplicate('Já existe outro item com esse nome.');return}item.nome=newName;item.comentarios=$('#f-item-comments').value.trim();item.foto=photoData;if(kind==='musica')item.autor=$('#f-item-author').value.trim();data.alunos.forEach(a=>{if(kind==='livro'){if(norm(a.livro)===norm(old))a.livro=newName;a.livrosHistorico.forEach(h=>{if(norm(h.nome)===norm(old))h.nome=newName})}else a.musicas.forEach(m=>{if(norm(m.nome)===norm(old)){m.nome=newName;m.autor=item.autor}})});ui.selectedItem={kind,name:newName};save();closeModal();toast('Item atualizado');render()}}
function ensureMonthClassRecords(offset=0){data.classRecords=data.classRecords||[];const base=monthDate(offset),last=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();data.alunos.forEach(a=>classSlots(a).forEach((slot,index)=>{const wanted=(DAYS.indexOf(slot.dia)+1)%7;for(let d=1;d<=last;d++){const date=new Date(base.getFullYear(),base.getMonth(),d),day=localISO(date);if(date.getDay()!==wanted||day<(a.desde||'0000-00-00')||(a.encerradoEm&&day>a.encerradoEm))continue;const id=`regular-${a.id}-${day}-${index}`;if(!data.classRecords.some(r=>r.id===id))data.classRecords.push({id,studentId:a.id,date:day,time:slot.hora,duration:slot.duracao||50,status:'pending',day:slot.dia})}}));save()}
function agendaSwitch(){return `<div class="agenda-switch"><button class="${ui.agendaView==='week'?'active':''}" data-agenda-view="week">Rotina semanal</button><button class="${ui.agendaView==='month'?'active':''}" data-agenda-view="month">Histórico mensal</button></div>`}
function schedule(){return ui.agendaView==='month'?monthlyAgenda():weeklyAgenda()}
function weeklyAgenda(){ensureWeekRecords();const monday=weekStart(),sunday=new Date(monday);sunday.setDate(monday.getDate()+6);const from=localISO(monday),to=localISO(sunday),records=data.classRecords.filter(r=>r.date>=from&&r.date<=to&&data.alunos.some(a=>a.id===r.studentId&&a.ativo!==false)),days=DAYS.filter((d,i)=>i<5||records.some(r=>r.day===d));return header('ROTINA E HISTÓRICO','Agenda','<button class="add" data-modal="aluno" aria-label="Novo aluno">＋</button>')+agendaSwitch()+`<div class="status-legend"><i class="held"></i>Realizada<i class="cancelled"></i>Cancelada<i class="missed"></i>Falta<i class="rescheduled"></i>Reagendada</div><div class="week-agenda">${days.map(day=>{const entries=records.filter(r=>r.day===day).sort((a,b)=>a.time.localeCompare(b.time));return `<section class="week-day"><div><b>${day}</b><small>${entries.length} ${entries.length===1?'aula':'aulas'}</small></div>${entries.length?entries.map(r=>classAgendaEntry(r)).join(''):'<p>—</p>'}</section>`}).join('')}</div>`}
function classAgendaEntry(r){const a=data.alunos.find(x=>x.id===r.studentId);return `<button class="class-entry status-${r.status||'pending'} ${r.rescheduled?'is-rescheduled':''}" data-class="${r.id}"><strong>${esc(r.time)}</strong><span>${esc(a?.nome||'Aluno')}</span>${r.rescheduled?'<em>Reagendada</em>':''}</button>`}
function monthlyAgenda(){ensureMonthClassRecords(ui.agendaMonth);const month=monthLabel(ui.agendaMonth),records=(data.classRecords||[]).filter(r=>r.date.startsWith(month.key)).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)),groups=[...new Set(records.map(r=>r.date))];return header('HISTÓRICO DE AULAS','Agenda')+agendaSwitch()+`<div class="month"><button data-agenda-month="-1">‹</button><b>${esc(month.label)}</b><button data-agenda-month="1">›</button></div><div class="status-legend"><i class="held"></i>Realizada<i class="cancelled"></i>Cancelada<i class="missed"></i>Falta<i class="rescheduled"></i>Reagendada</div><div class="month-history">${groups.length?groups.map(date=>`<section><div class="history-date"><b>${esc(new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}))}</b><small>${esc(DAYS[(new Date(`${date}T12:00:00`).getDay()+6)%7])}</small></div><div>${records.filter(r=>r.date===date).map(r=>classAgendaEntry(r)).join('')}</div></section>`).join(''):'<p class="empty">Nenhuma aula neste mês.</p>'}</div>`}
function paymentRow(p,a){return `<div class="payment" data-payment="${p.id}"><div class="person">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(p.ref)}</small></span></div><span class="payment-actions">${secretMoney(p.valor)}${p.pago?'<small class="ok">✓ Recebido</small>':`<button class="confirm" data-pay="${p.id}">Confirmar</button>`}</span></div>`}
function paymentDetail(){const p=data.pagamentos.find(x=>x.id===ui.selectedPayment),a=data.alunos.find(x=>x.id===p?.alunoId);if(!p||!a){ui.selectedPayment=null;return payments()}return header('PAGAMENTO',p.ref,'<button class="close" data-close-payment>×</button>')+`<section class="panel payment-detail"><button class="payment-person payment-student-link" data-student="${a.id}">${avatar(a)}<span><b>${esc(a.nome)}</b><small>${esc(a.plano)}${a.plano==='Por aula'?` · ${esc(money(a.valor))} por aula`:''}</small></span><i>›</i></button><div class="detail-line"><span>Status</span><b class="${p.pago?'ok':'pending-text'}">${p.pago?'Recebido':'Pendente'}</b></div><div class="detail-line"><span>Valor</span>${secretMoney(p.valor)}</div><div class="detail-line"><span>Confirmado em</span><b>${p.pagoEm?esc(p.pagoEm.split('-').reverse().join('/')):'Ainda não confirmado'}</b></div><label class="detail-note">Comentário<textarea data-payment-note placeholder="Comprovante, forma de pagamento ou observação...">${esc(p.notes||'')}</textarea></label>${p.pago?`<button class="cancel-payment" data-cancel-payment="${p.id}">Cancelar confirmação</button>`:`<button class="save" data-pay="${p.id}">Confirmar pagamento</button>`}</section>`}
function ensurePaymentsForMonth(offset=0){
  const date=monthDate(offset),key=monthKey(date),monthName=date.toLocaleDateString('pt-BR',{month:'long'}),year=date.getFullYear(),first=`${key}-01`,last=localISO(new Date(date.getFullYear(),date.getMonth()+1,0));
  data.alunos.filter(a=>a.ativo!==false&&(!a.desde||a.desde<=last)).forEach(a=>{
    if(a.plano==='Mensal'){
      const dueDate=a.desde&&a.desde>first?a.desde:first,autoKey=`${a.id}-monthly-${key}`,existing=data.pagamentos.find(p=>p.autoKey===autoKey||(!p.autoKey&&p.alunoId===a.id&&norm(p.ref).includes(norm(monthName))&&String(p.ref).includes(String(year))));
      if(existing){existing.autoKey=autoKey;existing.dueDate=existing.dueDate||dueDate}else data.pagamentos.push({id:Date.now()+Math.random(),alunoId:a.id,ref:`${monthName[0].toUpperCase()+monthName.slice(1)}/${year}`,valor:a.valor,pago:false,dueDate,autoKey});
    }else classSlots(a).forEach((slot,slotIndex)=>datesForSlotInMonth(date,slot).filter(day=>(!a.desde||day>=a.desde)&&(!a.encerradoEm||day<=a.encerradoEm)).forEach(day=>{const autoKey=`${a.id}-class-${day}-${slotIndex}`;if(!data.pagamentos.some(p=>p.autoKey===autoKey))data.pagamentos.push({id:Date.now()+Math.random(),alunoId:a.id,ref:`Aula ${day.split('-').reverse().slice(0,2).join('/')}`,valor:a.valor,pago:false,dueDate:day,autoKey})}));
  });save();
}
function ensureWeekRecords(){data.classRecords=data.classRecords||[];const monday=weekStart();data.alunos.filter(a=>a.ativo!==false).forEach(a=>classSlots(a).forEach((slot,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+DAYS.indexOf(slot.dia));const day=localISO(date);if((a.desde&&day<a.desde)||(a.encerradoEm&&day>a.encerradoEm))return;const id=`regular-${a.id}-${day}-${index}`;if(!data.classRecords.some(r=>r.id===id))data.classRecords.push({id,studentId:a.id,date:day,time:slot.hora,duration:slot.duracao||50,status:'pending',day:slot.dia})}));save()}
function ensureMonthClassRecords(offset=0){data.classRecords=data.classRecords||[];const base=monthDate(offset),last=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();data.alunos.forEach(a=>classSlots(a).forEach((slot,index)=>{const wanted=(DAYS.indexOf(slot.dia)+1)%7;for(let d=1;d<=last;d++){const date=new Date(base.getFullYear(),base.getMonth(),d),day=localISO(date);if(date.getDay()!==wanted||(a.desde&&day<a.desde)||(a.encerradoEm&&day>a.encerradoEm))continue;const id=`regular-${a.id}-${day}-${index}`;if(!data.classRecords.some(r=>r.id===id))data.classRecords.push({id,studentId:a.id,date:day,time:slot.hora,duration:slot.duracao||50,status:'pending',day:slot.dia})}}));save()}
function stopStudent(studentId){const a=data.alunos.find(x=>x.id===studentId);if(!a)return;if(a.ativo===false){a.ativo=true;delete a.encerradoEm;ensurePaymentsForMonth(0);save();toast('Aluno reativado');render();return}const end=todayISO(),monthStart=end.slice(0,7)+'-01',monthEnd=localISO(new Date(new Date().getFullYear(),new Date().getMonth()+1,0));a.ativo=false;a.encerradoEm=end;data.classRecords=(data.classRecords||[]).filter(r=>r.studentId!==a.id||r.date<=end);data.pagamentos=data.pagamentos.filter(p=>p.alunoId!==a.id||!p.dueDate||p.dueDate<=end);if(confirm('Excluir também todos os pagamentos restantes deste aluno no mês atual? Isso pode incluir pagamentos já confirmados.'))data.pagamentos=data.pagamentos.filter(p=>p.alunoId!==a.id||!p.dueDate||p.dueDate<monthStart||p.dueDate>monthEnd);save();toast('Aulas encerradas; registros futuros removidos');render()}
function openProfileSettings(){let photoData=data.settings.foto||'';modalShell('Dados da professora',`${photoField('Foto da professora','f-photo',photoData)}${field('Seu nome','f-teacher','text',data.settings.teacherName||'','placeholder="Ex.: Maria Silva"')}${field('Nome da escola','f-school','text',data.settings.schoolName||'','placeholder="Ex.: Escola de Música Harmonia"')}<section class="erase-zone"><b>Apagar dados do aplicativo</b><p>Remove alunos, aulas, pagamentos, livros e repertório. Os dados da professora serão mantidos.</p><button type="button" class="danger-action" id="open-erase-data">Apagar todos os dados</button></section>`);bindPhotoEditor('f-photo',photoData,file=>photoData=file);$('#open-erase-data').onclick=()=>{closeModal();openEraseAllDataModal()};$('.modal').onsubmit=e=>{e.preventDefault();data.settings.teacherName=$('#f-teacher').value.trim();data.settings.schoolName=$('#f-school').value.trim();data.settings.foto=photoData;save();closeModal();toast('Dados atualizados');render()}}
function openEraseAllDataModal(){modalShell('Apagar todos os dados',`<div class="erase-warning"><b>Esta ação não pode ser desfeita.</b><p>Todos os alunos, aulas, pagamentos, livros e repertório serão apagados. O perfil da professora será preservado.</p></div><label>Para confirmar, digite exatamente:<strong>erase all data</strong><input id="erase-confirmation" type="text" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" data-lpignore="true" data-1p-ignore="true" name="compasso-delete-confirmation-${Date.now()}" required></label>`);$('.modal .save').textContent='Apagar definitivamente';$('.modal').onsubmit=e=>{e.preventDefault();if($('#erase-confirmation').value!=='erase all data'){showDuplicate('A frase não corresponde. Digite exatamente: erase all data');return}const teacher={...data.settings};data={alunos:[],pagamentos:[],livros:[],repertorio:[],classRecords:[],settings:teacher,demoKurtSeyit:true,dataErased:true};ui={...ui,page:'inicio',selectedStudent:null,selectedItem:null,selectedPayment:null,selectedClass:null,search:'',paymentMonth:0,agendaMonth:0};save();closeModal();toast('Todos os dados foram apagados');render()}}
function photoField(label,id,current=''){const src=photoSource(current);return `<div class="photo-editor"><span>${esc(label)}</span><div class="photo-editor-preview ${src?'has-photo':''}" id="${id}-preview" ${src?`style="${photoStyle(current)}"`:''}><i>♬</i><button type="button" class="camera-action" data-camera-for="${id}" aria-label="Abrir câmera"><span></span></button><input class="camera-file-fallback" id="${id}" type="file" accept="image/*" capture="environment" tabindex="-1"></div><small>Toque na câmera para fotografar.</small></div>`}
function bindPhotoEditor(id,current,onChange){const input=$(`#${id}`),preview=$(`#${id}-preview`),button=$(`[data-camera-for="${id}"]`);if(!input)return;const apply=photo=>{if(preview){preview.classList.add('has-photo');preview.setAttribute('style',photoStyle(photo))}onChange(photo)};input.onchange=()=>readPhoto(input,apply);if(button)button.onclick=()=>openDirectCamera(input,apply)}
async function openDirectCamera(fallbackInput,onCapture){let stream;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});document.body.insertAdjacentHTML('beforeend',`<div class="camera-screen"><video autoplay playsinline muted></video><div class="camera-bar"><button type="button" class="camera-cancel">×</button><button type="button" class="camera-shutter" aria-label="Tirar foto"><i></i></button><button type="button" class="camera-gallery" aria-label="Escolher foto">▧</button></div></div>`);const screen=$('.camera-screen'),video=$('video',screen),stop=()=>{stream?.getTracks().forEach(track=>track.stop());screen.remove()};video.srcObject=stream;await video.play();$('.camera-cancel',screen).onclick=stop;$('.camera-gallery',screen).onclick=()=>{stop();fallbackInput.click()};$('.camera-shutter',screen).onclick=()=>{if(!video.videoWidth){toast('A câmera ainda está iniciando');return}const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);const src=canvas.toDataURL('image/jpeg',.88);stop();openCropper(src,onCapture)}}catch(error){stream?.getTracks().forEach(track=>track.stop());if(error?.name==='NotAllowedError'||error?.name==='PermissionDeniedError'){toast('Permita o uso da câmera nas configurações do Compasso ou do Chrome');return}fallbackInput.click()}}
populateDemo();
save();render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
